import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'auth_repository.dart';
import 'card_repository.dart';
import 'deck_repository.dart';
import 'meta_repository.dart';
import 'recommended_deck_repository.dart';
import 'profile_repository.dart';
import 'opponent_repository.dart';
import 'match_record_repository.dart';
import 'meetup_repository.dart';
import 'live_location_repository.dart';

final authRepositoryProvider = Provider<AuthRepository>((ref) => SupabaseAuthRepository());
final cardRepositoryProvider = Provider<CardRepository>((ref) => SupabaseCardRepository());
final deckRepositoryProvider = Provider<DeckRepository>((ref) => MixedDeckRepository());
final metaRepositoryProvider = Provider<MetaRepository>((ref) => SupabaseMetaRepository());
final recommendedDeckRepositoryProvider = Provider<RecommendedDeckRepository>((ref) => SupabaseRecommendedDeckRepository());
final profileRepositoryProvider = Provider<ProfileRepository>((ref) => SupabaseProfileRepository());
final opponentRepositoryProvider = Provider<OpponentRepository>((ref) => SupabaseOpponentRepository());
final matchRecordRepositoryProvider = Provider<MatchRecordRepository>((ref) => SupabaseMatchRecordRepository());
final meetupRepositoryProvider = Provider<MeetupRepository>((ref) => SupabaseMeetupRepository());
final liveLocationRepositoryProvider = Provider<LiveLocationRepository>((ref) => SupabaseLiveLocationRepository());
